pipeline {

    agent any //the pipeline will run on any available jenkins agents. Jenkins agents are executor nodes (linux or windows)

    stages {
        stage ('Build with unit tests') {
            steps {
                script {
                    stageName = 'Build with unit tests'
                    echo "Build maven artifact from ${env.BRANCH_NAME} branch."
                    mvn "clean install"
                }
            }
        }
    }
}