pipeline {

    agent any //the pipeline will run on any available jenkins agents. Jenkins agents are executor nodes (linux or windows)

    tools {
        maven 'Maven 3.9.6'
    }

    stages {
        stage ('Build with unit tests') {
            steps {
                script {
                    stageName = 'Build with unit tests'
                    echo "Build maven artifact from ${env.BRANCH_NAME} branch."
                    sh "mvn clean install"
                }
            }
        }
        stage ('Verify code formatting') {
            steps {
                script {
                    stageName = 'Verify code formatting'
                    try {
                        sh "git status"
                        sh "git status | grep -c \'nothing to commit, working tree clean\'"
                    } catch (err) {
                        echo "Please run a \'mvn clean install\' locally and commit the changes!"
                        throw err
                    }
                }
            }
        }
        stage ('Publish artifact to Github maven repository') {
            steps {
                script {
                    stageName = 'Publish artifact to Github maven repository'
                    echo "Run maven deploy"
                    sh "mvn deploy"
                }
            }
        }
    }
}